### ISSUE TITLE
Is there a way to get the player ID and player name?

### ISSUE THREAD

**Issue by interpre** [jrmarkham/game_service_connect#1]

**Comment by jrmarkham** [comment]
This isn't a code issue. It is a document issue. When you call: GameServicesConnect.signIn a successful response will include an account object w/ id and displayName.

**Comment by interpre** [comment]
I'm not sure if it is called player name or gamer name. But I'm referring to the name uses by the game service which is like not a real name. If I'm not mistaken, display name is different which is like the real name.

**Comment by jrmarkham** [comment]
Yes, the display name is the gamer name, not the real name. I am not passing back any data but those two things. I used the var name "displayName" because in the game I am building I use that var in the game.

**Comment by interpre** [comment]
I see, thanks for this clarification

**Comment by interpre** [comment]
How about the email address, is it included also?

**Comment by jrmarkham** [comment]
> How about the email address, is it included also?

Not currently. Just id and gamerName.
